// CSE 154 ASCIIMation
// This is my custom animation to be used by the overall program.
// It was automatically generated by the StringMaker tool.
// (Paste this code as the contents of your myanimation.js file.)

var CUSTOM =
"  \n" + 
"  \n" + 
"  \n" + 
"  \n" + 
"  \n" + 
"  \n" + 
"  \n" + 
"  \n" + 
"  \n" + 
"  \n" + 
"  \n" + 
"=====\n" + 
"  \n" + 
"  \n" + 
"  \n" + 
"  \n" + 
"  \n" + 
"  \n" + 
"  \n" + 
"  \n" + 
"  \n" + 
"  \n" + 
"  \n" + 
"=====\n" + 
"  \n" + 
"  \n" + 
"  \n" + 
"  \n" + 
"  \n" + 
"  \n" + 
"  \n" + 
"  \n" + 
"  \n" + 
"  \n" + 
"  \n" + 
"=====\n" + 
"  \n" + 
"  \n" + 
"  \n" + 
"  \n" + 
"  \n" + 
"  \n" + 
"  \n" + 
"  \n" + 
"  \n" + 
"  \n" + 
"  \n" + 
"=====\n" + 
"  \n" + 
"  \n" + 
"  \n" + 
"  \n" + 
"  \n" + 
"  \n" + 
"  \n" + 
"  \n" + 
"  \n" + 
"  \n" + 
"  \n" + 
"=====\n" + 
"  \n" + 
"  \n" + 
"  \n" + 
"  \n" + 
"  \n" + 
"  \n" + 
"  \n" + 
"  \n" + 
"  \n" + 
"  \n" + 
"       STAR WARS\n" + 
"=====\n" + 
"  \n" + 
"  \n" + 
"  \n" + 
"  \n" + 
"  \n" + 
"  \n" + 
"  \n" + 
"  \n" + 
"  \n" + 
"       STAR WARS\n" + 
" \n" + 
"=====\n" + 
"  \n" + 
"  \n" + 
"  \n" + 
"  \n" + 
"  \n" + 
"  \n" + 
"  \n" + 
"  \n" + 
"       STAR WARS\n" + 
" \n" + 
" \n" + 
"=====\n" + 
"  \n" + 
"  \n" + 
"  \n" + 
"  \n" + 
"  \n" + 
"  \n" + 
"  \n" + 
"       STAR WARS\n" + 
" \n" + 
" \n" + 
" \n" + 
"=====\n" + 
"  \n" + 
"  \n" + 
"  \n" + 
"  \n" + 
"  \n" + 
"  \n" + 
"       STAR WARS\n" + 
" \n" + 
" \n" + 
" \n" + 
"       Episode IV\n" + 
"=====\n" + 
"  \n" + 
"  \n" + 
"  \n" + 
"  \n" + 
"  \n" + 
"       STAR WARS\n" + 
" \n" + 
" \n" + 
" \n" + 
"       Episode IV\n" + 
"       A NEW HOPE\n" + 
"=====\n" + 
"  \n" + 
"  \n" + 
"  \n" + 
"  \n" + 
"       STAR WARS\n" + 
" \n" + 
" \n" + 
" \n" + 
"       Episode IV\n" + 
"       A NEW HOPE\n" + 
" \n" + 
"=====\n" + 
"  \n" + 
"  \n" + 
"  \n" + 
"       STAR WARS\n" + 
" \n" + 
" \n" + 
" \n" + 
"       Episode IV\n" + 
"       A NEW HOPE\n" + 
" \n" + 
" \n" + 
"=====\n" + 
"  \n" + 
"  \n" + 
"       STAR WARS\n" + 
" \n" + 
" \n" + 
" \n" + 
"       Episode IV\n" + 
"       A NEW HOPE\n" + 
" \n" + 
" \n" + 
"It is a period of civil war.\n" + 
"=====\n" + 
"  \n" + 
"       STAR WARS\n" + 
" \n" + 
" \n" + 
" \n" + 
"       Episode IV\n" + 
"       A NEW HOPE\n" + 
" \n" + 
" \n" + 
"It is a period of civil war.\n" + 
"Rebel spaceships, striking\n" + 
"=====\n" + 
"       STAR WARS\n" + 
" \n" + 
" \n" + 
" \n" + 
"       Episode IV\n" + 
"       A NEW HOPE\n" + 
" \n" + 
" \n" + 
"It is a period of civil war.\n" + 
"Rebel spaceships, striking\n" + 
"from a hidden base, have won\n" + 
"=====\n" + 
" \n" + 
" \n" + 
" \n" + 
"       Episode IV\n" + 
"       A NEW HOPE\n" + 
" \n" + 
" \n" + 
"It is a period of civil war.\n" + 
"Rebel spaceships, striking\n" + 
"from a hidden base, have won\n" + 
"their first victory against\n" + 
"=====\n" + 
" \n" + 
" \n" + 
"       Episode IV\n" + 
"       A NEW HOPE\n" + 
" \n" + 
" \n" + 
"It is a period of civil war.\n" + 
"Rebel spaceships, striking\n" + 
"from a hidden base, have won\n" + 
"their first victory against\n" + 
"the evil Galactic Empire.\n" + 
"=====\n" + 
" \n" + 
"       Episode IV\n" + 
"       A NEW HOPE\n" + 
" \n" + 
" \n" + 
"It is a period of civil war.\n" + 
"Rebel spaceships, striking\n" + 
"from a hidden base, have won\n" + 
"their first victory against\n" + 
"the evil Galactic Empire.\n" + 
" \n" + 
"=====\n" + 
"       Episode IV\n" + 
"       A NEW HOPE\n" + 
" \n" + 
" \n" + 
"It is a period of civil war.\n" + 
"Rebel spaceships, striking\n" + 
"from a hidden base, have won\n" + 
"their first victory against\n" + 
"the evil Galactic Empire.\n" + 
" \n" + 
"During the battle, Rebel\n" + 
"=====\n" + 
"       A NEW HOPE\n" + 
" \n" + 
" \n" + 
"It is a period of civil war.\n" + 
"Rebel spaceships, striking\n" + 
"from a hidden base, have won\n" + 
"their first victory against\n" + 
"the evil Galactic Empire.\n" + 
" \n" + 
"During the battle, Rebel\n" + 
"spies managed to steal secret\n" + 
"=====\n" + 
" \n" + 
" \n" + 
"It is a period of civil war.\n" + 
"Rebel spaceships, striking\n" + 
"from a hidden base, have won\n" + 
"their first victory against\n" + 
"the evil Galactic Empire.\n" + 
" \n" + 
"During the battle, Rebel\n" + 
"spies managed to steal secret\n" + 
"plans to the Empire\'s\n" + 
"=====\n" + 
" \n" + 
"It is a period of civil war.\n" + 
"Rebel spaceships, striking\n" + 
"from a hidden base, have won\n" + 
"their first victory against\n" + 
"the evil Galactic Empire.\n" + 
" \n" + 
"During the battle, Rebel\n" + 
"spies managed to steal secret\n" + 
"plans to the Empire\'s\n" + 
"ultimate weapon, the DEATH\n" + 
"=====\n" + 
"It is a period of civil war.\n" + 
"Rebel spaceships, striking\n" + 
"from a hidden base, have won\n" + 
"their first victory against\n" + 
"the evil Galactic Empire.\n" + 
" \n" + 
"During the battle, Rebel\n" + 
"spies managed to steal secret\n" + 
"plans to the Empire\'s\n" + 
"ultimate weapon, the DEATH\n" + 
"STAR, an armored space\n" + 
"=====\n" + 
"Rebel spaceships, striking\n" + 
"from a hidden base, have won\n" + 
"their first victory against\n" + 
"the evil Galactic Empire.\n" + 
" \n" + 
"During the battle, Rebel\n" + 
"spies managed to steal secret\n" + 
"plans to the Empire\'s\n" + 
"ultimate weapon, the DEATH\n" + 
"STAR, an armored space\n" + 
"station with enough power\n" + 
"=====\n" + 
"from a hidden base, have won\n" + 
"their first victory against\n" + 
"the evil Galactic Empire.\n" + 
" \n" + 
"During the battle, Rebel\n" + 
"spies managed to steal secret\n" + 
"plans to the Empire\'s\n" + 
"ultimate weapon, the DEATH\n" + 
"STAR, an armored space\n" + 
"station with enough power\n" + 
"to destroy an entire planet.\n" + 
"=====\n" + 
"their first victory against\n" + 
"the evil Galactic Empire.\n" + 
" \n" + 
"During the battle, Rebel\n" + 
"spies managed to steal secret\n" + 
"plans to the Empire\'s\n" + 
"ultimate weapon, the DEATH\n" + 
"STAR, an armored space\n" + 
"station with enough power\n" + 
"to destroy an entire planet.\n" + 
" \n" + 
"=====\n" + 
"the evil Galactic Empire.\n" + 
" \n" + 
"During the battle, Rebel\n" + 
"spies managed to steal secret\n" + 
"plans to the Empire\'s\n" + 
"ultimate weapon, the DEATH\n" + 
"STAR, an armored space\n" + 
"station with enough power\n" + 
"to destroy an entire planet.\n" + 
" \n" + 
"Pursued by the Empire\'s\n" + 
"=====\n" + 
" \n" + 
"During the battle, Rebel\n" + 
"spies managed to steal secret\n" + 
"plans to the Empire\'s\n" + 
"ultimate weapon, the DEATH\n" + 
"STAR, an armored space\n" + 
"station with enough power\n" + 
"to destroy an entire planet.\n" + 
" \n" + 
"Pursued by the Empire\'s\n" + 
"sinister agents, Princess\n" + 
"=====\n" + 
"During the battle, Rebel\n" + 
"spies managed to steal secret\n" + 
"plans to the Empire\'s\n" + 
"ultimate weapon, the DEATH\n" + 
"STAR, an armored space\n" + 
"station with enough power\n" + 
"to destroy an entire planet.\n" + 
" \n" + 
"Pursued by the Empire\'s\n" + 
"sinister agents, Princess\n" + 
"Leia races home aboard her\n" + 
"=====\n" + 
"spies managed to steal secret\n" + 
"plans to the Empire\'s\n" + 
"ultimate weapon, the DEATH\n" + 
"STAR, an armored space\n" + 
"station with enough power\n" + 
"to destroy an entire planet.\n" + 
" \n" + 
"Pursued by the Empire\'s\n" + 
"sinister agents, Princess\n" + 
"Leia races home aboard her\n" + 
"starship, custodian of the\n" + 
"=====\n" + 
"plans to the Empire\'s\n" + 
"ultimate weapon, the DEATH\n" + 
"STAR, an armored space\n" + 
"station with enough power\n" + 
"to destroy an entire planet.\n" + 
" \n" + 
"Pursued by the Empire\'s\n" + 
"sinister agents, Princess\n" + 
"Leia races home aboard her\n" + 
"starship, custodian of the\n" + 
"stolen plans that can save her\n" + 
"=====\n" + 
"ultimate weapon, the DEATH\n" + 
"STAR, an armored space\n" + 
"station with enough power\n" + 
"to destroy an entire planet.\n" + 
" \n" + 
"Pursued by the Empire\'s\n" + 
"sinister agents, Princess\n" + 
"Leia races home aboard her\n" + 
"starship, custodian of the\n" + 
"stolen plans that can save her\n" + 
"people and restore\n" + 
"=====\n" + 
"STAR, an armored space\n" + 
"station with enough power\n" + 
"to destroy an entire planet.\n" + 
" \n" + 
"Pursued by the Empire\'s\n" + 
"sinister agents, Princess\n" + 
"Leia races home aboard her\n" + 
"starship, custodian of the\n" + 
"stolen plans that can save her\n" + 
"people and restore\n" + 
"freedom to the galaxy....\n" + 
"=====\n" + 
"station with enough power\n" + 
"to destroy an entire planet.\n" + 
" \n" + 
"Pursued by the Empire\'s\n" + 
"sinister agents, Princess\n" + 
"Leia races home aboard her\n" + 
"starship, custodian of the\n" + 
"stolen plans that can save her\n" + 
"people and restore\n" + 
"freedom to the galaxy....\n" + 
"  \n" + 
"=====\n" + 
"to destroy an entire planet.\n" + 
" \n" + 
"Pursued by the Empire\'s\n" + 
"sinister agents, Princess\n" + 
"Leia races home aboard her\n" + 
"starship, custodian of the\n" + 
"stolen plans that can save her\n" + 
"people and restore\n" + 
"freedom to the galaxy....\n" + 
"  \n" + 
"  \n" + 
"=====\n" + 
" \n" + 
"Pursued by the Empire\'s\n" + 
"sinister agents, Princess\n" + 
"Leia races home aboard her\n" + 
"starship, custodian of the\n" + 
"stolen plans that can save her\n" + 
"people and restore\n" + 
"freedom to the galaxy....\n" + 
"  \n" + 
"  \n" + 
"  \n" + 
"=====\n" + 
"Pursued by the Empire\'s\n" + 
"sinister agents, Princess\n" + 
"Leia races home aboard her\n" + 
"starship, custodian of the\n" + 
"stolen plans that can save her\n" + 
"people and restore\n" + 
"freedom to the galaxy....\n" + 
"  \n" + 
"  \n" + 
"  \n" + 
"  \n" + 
"=====\n" + 
"sinister agents, Princess\n" + 
"Leia races home aboard her\n" + 
"starship, custodian of the\n" + 
"stolen plans that can save her\n" + 
"people and restore\n" + 
"freedom to the galaxy....\n" + 
"  \n" + 
"  \n" + 
"  \n" + 
"  \n" + 
"  \n" + 
"=====\n" + 
"Leia races home aboard her\n" + 
"starship, custodian of the\n" + 
"stolen plans that can save her\n" + 
"people and restore\n" + 
"freedom to the galaxy....\n" + 
"  \n" + 
"  \n" + 
"  \n" + 
"  \n" + 
"  \n" + 
"  \n" + 
"=====\n" + 
"starship, custodian of the\n" + 
"stolen plans that can save her\n" + 
"people and restore\n" + 
"freedom to the galaxy....\n" + 
"  \n" + 
"  \n" + 
"  \n" + 
"  \n" + 
"  \n" + 
"  \n" + 
"  \n" + 
"=====\n" + 
"stolen plans that can save her\n" + 
"people and restore\n" + 
"freedom to the galaxy....\n" + 
"  \n" + 
"  \n" + 
"  \n" + 
"  \n" + 
"  \n" + 
"  \n" + 
"  \n" + 
"  \n" + 
"=====\n" + 
"people and restore\n" + 
"freedom to the galaxy....\n" + 
"  \n" + 
"  \n" + 
"  \n" + 
"  \n" + 
"  \n" + 
"  \n" + 
"  \n" + 
"  \n" + 
"  \n" + 
"=====\n" + 
"freedom to the galaxy....\n" + 
"  \n" + 
"  \n" + 
"  \n" + 
"  \n" + 
"  \n" + 
"  \n" + 
"  \n" + 
"  \n" + 
"  \n" + 
"  \n" + 
"=====\n" + 
"  \n" + 
"  \n" + 
"  \n" + 
"  \n" + 
"  \n" + 
"  \n" + 
"  \n" + 
"  \n" + 
"  \n" + 
"  \n" + 
"  \n" + 
"=====\n" + 
"  \n" + 
"  \n" + 
"  \n" + 
"  \n" + 
"  \n" + 
"  \n" + 
"  \n" + 
"  \n" + 
"  \n" + 
"  \n" + 
"  \n" + 
"=====\n" + 
"  \n" + 
"  \n" + 
"  \n" + 
"  \n" + 
"  \n" + 
"  \n" + 
"  \n" + 
"  \n" + 
"  \n" + 
"  \n" + 
"  \n" + 
"=====\n" + 
"  \n" + 
"  \n" + 
"  \n" + 
"  \n" + 
"  \n" + 
"  \n" + 
"  \n" + 
"  \n" + 
"  \n" + 
"  \n" + 
"  \n" + 
"=====\n" + 
"  \n" + 
"  \n" + 
"  \n" + 
"  \n" + 
"  \n" + 
"  \n" + 
"  \n" + 
"  \n" + 
"  \n" + 
"  \n" + 
"  \n" + 
"=====\n" + 
"  \n" + 
"  \n" + 
"  \n" + 
"  \n" + 
"  \n" + 
"  \n" + 
"  \n" + 
"  \n" + 
"  \n" + 
"  \n" + 
"  \n" + 
"=====\n" + 
"  \n" + 
"  \n" + 
"  \n" + 
"  \n" + 
"  \n" + 
"  \n" + 
"  \n" + 
"  \n" + 
"  \n" + 
"  \n" + 
"  \n" + 
"=====\n";

ANIMATIONS["Custom"] = ANIMATIONS["custom"] = ANIMATIONS["CUSTOM"] = CUSTOM;
